server:
  port: 8083


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true